// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyQP7Abwa6F5T8G8D7wkvhJXOaLdCaGc',
    appId: '1:79111689275:web:1f720d69d462fb69fd781e',
    messagingSenderId: '79111689275',
    projectId: 'reading-turtle-173a8',
    authDomain: 'reading-turtle-173a8.firebaseapp.com',
    storageBucket: 'reading-turtle-173a8.firebasestorage.app',
    measurementId: 'G-5KNGG8SPQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyQP7Abwa6F5T8G8D7wkvhJXOaLdCaGc',
    appId: '1:79111689275:android:your_android_app_id_here',
    messagingSenderId: '79111689275',
    projectId: 'reading-turtle-173a8',
    storageBucket: 'reading-turtle-173a8.firebasestorage.app',
    measurementId: 'G-5KNGG8SPQN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFyQP7Abwa6F5T8G8D7wkvhJXOaLdCaGc',
    appId: '1:79111689275:ios:your_ios_app_id_here',
    messagingSenderId: '79111689275',
    projectId: 'reading-turtle-173a8',
    storageBucket: 'reading-turtle-173a8.firebasestorage.app',
    iosBundleId: 'com.example.readingTurtle',
    measurementId: 'G-5KNGG8SPQN',
  );
}
